[project]
name = "b25-tour"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "shiny>=1.5.0",
]

[tool.uv.workspace]
members = [
    "seaborn",
]
